name: Lint, Test & Build

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4.0.0

      - run: pnpm dlx nx-cloud start-ci-run --distribute-on="4 linux-medium-js" --stop-agents-after="build"

      - uses: actions/setup-node@v4.1.0
        with:
          node-version: 22
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4.1.2

      - run: pnpm exec nx affected -t lint format:check test build
